// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn_7dCojdy7ya9Mpl0Nf65VY62-qdirlU',
    appId: '1:394129669406:web:1cf78f608284ac7b6e1d0f',
    messagingSenderId: '394129669406',
    projectId: 'cropx-6f03a',
    authDomain: 'cropx-6f03a.firebaseapp.com',
    storageBucket: 'cropx-6f03a.appspot.com',
    measurementId: 'G-7KJ1V80VFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR_6lVgkJbRBaD1keo9b3a1c6z1CD2rio',
    appId: '1:394129669406:android:a5c665369b7af6bb6e1d0f',
    messagingSenderId: '394129669406',
    projectId: 'cropx-6f03a',
    storageBucket: 'cropx-6f03a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7uv8srsc3isGVszacOrFAcwGkxEACjas',
    appId: '1:394129669406:ios:226b60dcb663c3986e1d0f',
    messagingSenderId: '394129669406',
    projectId: 'cropx-6f03a',
    storageBucket: 'cropx-6f03a.appspot.com',
    iosBundleId: 'com.example.cropx',
  );
}
